services:
  db:
    image: pgvector/pgvector:pg16
    container_name: fin-ai-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=findb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data